version: '3.7'
services:

  traefik:
    # Use the latest Traefik image
    image: traefik:v2.5

  php:
    image: serversideup/php:8.2-fpm-nginx
    working_dir: /var/www/html

  mariadb:
    image: mariadb:10.7
  
  node:
    image: node:lts
  
  redis:
    image: redis:6

  mailhog:
    image: mailhog/mailhog:latest